// <auto-generated />
using System;
using DatabaseLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseLib.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714025548_AddAccountId")]
    partial class AddAccountId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseLib.Entities.EquipmentEntity", b =>
                {
                    b.Property<long>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("equipment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EquipmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EquipmentDataJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("equipment_data");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("EquipmentId");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_player_id");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("DatabaseLib.Entities.GameActivityEntity", b =>
                {
                    b.Property<long>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("activity_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ActivityId"));

                    b.Property<string>("ActivityDataJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("activity_data");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activity_type");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.HasKey("ActivityId");

                    b.HasIndex("ActivityDataJson")
                        .HasDatabaseName("ix_activity_data_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ActivityDataJson"), "gin");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_game_activity_player_id");

                    b.HasIndex("ActivityType", "CreatedAt")
                        .HasDatabaseName("ix_game_activity_type_data");

                    b.HasIndex("PlayerId", "CreatedAt")
                        .HasDatabaseName("ix_game_activity_player_data");

                    b.ToTable("game_activity", (string)null);
                });

            modelBuilder.Entity("DatabaseLib.Entities.InventoryEntity", b =>
                {
                    b.Property<long>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InventoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("InventoryDataJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("inventory_data");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("MaxSlots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("max_slots");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("InventoryId");

                    b.HasIndex("InventoryDataJson")
                        .HasDatabaseName("ix_inventory_data_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("InventoryDataJson"), "gin");

                    b.HasIndex("LastUpdated")
                        .HasDatabaseName("ix_inventory_last_updated");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_player_id");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("DatabaseLib.Entities.PlayerEntity", b =>
                {
                    b.Property<long>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("player_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlayerId"));

                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("experience");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<string>("LoginToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("login_token");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("player_name");

                    b.Property<string>("PlayerSettingsJson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("player_settings");

                    b.Property<long>("TotalPlayTimeMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_play_time_minutes");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("PlayerId");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_players_account_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_players_created_at");

                    b.HasIndex("LoginToken")
                        .HasDatabaseName("ix_players_login_token");

                    b.HasIndex("PlayerName")
                        .IsUnique()
                        .HasDatabaseName("ix_players_player_name");

                    b.HasIndex("PlayerSettingsJson")
                        .HasDatabaseName("ix_players_settings_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PlayerSettingsJson"), "gin");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("DatabaseLib.Entities.EquipmentEntity", b =>
                {
                    b.HasOne("DatabaseLib.Entities.PlayerEntity", "Player")
                        .WithOne()
                        .HasForeignKey("DatabaseLib.Entities.EquipmentEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DatabaseLib.Entities.GameActivityEntity", b =>
                {
                    b.HasOne("DatabaseLib.Entities.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DatabaseLib.Entities.InventoryEntity", b =>
                {
                    b.HasOne("DatabaseLib.Entities.PlayerEntity", "Player")
                        .WithOne()
                        .HasForeignKey("DatabaseLib.Entities.InventoryEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
