// [자동 생성] Protocol.proto 파일을 기반으로 자동 생성된 코드입니다.
// Target: Client

public enum PacketID
{
	C_EnterGame = 0,
	S_EnterGame = 1,
	S_LeaveGame = 2,
	S_Spawn = 3,
	S_Despawn = 4,
	C_Move = 5,
	S_Move = 6,
	C_Chat = 7,
	S_Chat = 8,
	S_PlayerUpdate = 9,
	S_PlayerStat = 10,
	C_PlayerInfo = 11,
	C_UseSkill = 12,
	S_Damage = 13,
	S_Heal = 14,
	S_LevelUp = 15,
	C_InventoryRequest = 16,
	S_InventoryData = 17,
	C_UseItem = 18,
	S_UseItem = 19,
	C_EquipItem = 20,
	S_ItemEquipped = 21,
	C_UnequipItem = 22,
	S_ItemUnequipped = 23,
	S_ItemAdded = 24,
	S_InventoryUpdate = 25,
	S_MonsterDie = 26,
	S_MonsterUpdate = 27,
	C_ChangeRoom = 28,
	S_ChangeRoom = 29,
	C_Ping = 10000,
	S_Pong = 10001,
}
